Repository FAST-gamsungcoding/BE_MiniProject, pull requests merged in 2023-11, with the labels that each got.

#6 `docker-compose.yml` 설정 파일의 잘못된 부분 수정
  .env.example
  .gitignore
  docker-compose.yml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
Labels: Fix, Chore

#8 Member 엔티티 및 레포지토리 추가
  src/main/java/com/gamsung/backend/domain/member/entity/Member.java
  src/main/java/com/gamsung/backend/domain/member/repository/MemberRepository.java
Labels: Feat

#11 기본적인 시큐리티 설정과 필터 설정 추가
  src/main/java/com/gamsung/backend/global/config/SecurityConfig.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
Labels: Feat

#15 JWT 토큰 발급 클래스 추가
  .env.example
  build.gradle
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java
  src/main/java/com/gamsung/backend/global/jwt/exception/JwtInvalidTokenException.java
  src/main/java/com/gamsung/backend/global/jwt/exception/JwtTokenExpiredException.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-test.yaml
  src/main/resources/application.yaml
  src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
Labels: Feat, Chore

#16 jwt 리프레시 토큰 저장을 위한 Redis 추가
  .env.example
  build.gradle
  docker-compose.yml
  src/main/java/com/gamsung/backend/BackendApplication.java
  src/main/java/com/gamsung/backend/global/config/RedisConfig.java
  src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java
  src/main/java/com/gamsung/backend/global/jwt/entity/JwtRedisEntity.java
  src/main/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepository.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/main/resources/application.yaml
  src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
Labels: Feat

#18 JwtPair 추가
  src/main/java/com/gamsung/backend/global/jwt/JwtPair.java
Labels: Feat

#19 JwtFilter 추가
  src/main/java/com/gamsung/backend/global/config/SecurityConfig.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/main/java/com/gamsung/backend/global/security/jwt/JwtAuthenticationProvider.java
  src/main/java/com/gamsung/backend/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/gamsung/backend/global/security/jwt/JwtFilter.java
Labels: Feat

#24 멤버 컨트롤러 및 서비스 추가
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/domain/member/controller/request/MemberControllerLoginRequest.java
  src/main/java/com/gamsung/backend/domain/member/controller/request/MemberControllerRegisterEmailCheckRequest.java
  src/main/java/com/gamsung/backend/domain/member/controller/request/MemberControllerRegisterRequest.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLogoutResponse.java
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberRegisterEmailCheckResponse.java
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberRegisterResponse.java
  src/main/java/com/gamsung/backend/domain/member/exception/MemberAlreadyExistedException.java
  src/main/java/com/gamsung/backend/domain/member/exception/MemberLoginWrongPasswordException.java
  src/main/java/com/gamsung/backend/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/gamsung/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/main/java/com/gamsung/backend/global/common/ApiResponse.java
  src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java
  src/test/http/member/login.http
  src/test/http/member/logout.http
  src/test/http/member/register.http
  src/test/http/member/registerEmailCheck.http
Labels: Feat, Test

#26 Feat : Swagger 코드 작성 및 테스트 데이터 작성
  build.gradle
  src/main/java/com/gamsung/backend/BackendApplication.java
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java
  src/main/java/com/gamsung/backend/global/common/BaseTime.java
  src/main/java/com/gamsung/backend/global/config/SwaggerConfig.java
  src/main/java/com/gamsung/backend/global/config/SwaggerDescriptionConfig.java
Labels: Docs, Test

#28 액세스 토큰 리프레시 API 추가
  src/main/java/com/gamsung/backend/global/config/SecurityConfig.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenRequest.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationToken.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtFilter.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/http/member/refresh.http
Labels: Fix, Feat, Test

#30 Cors 세팅 추가
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java
  src/main/java/com/gamsung/backend/global/common/ControllerResponse.java
  src/main/java/com/gamsung/backend/global/config/CorsConfig.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
Labels: Feat, Refactor

#36 레디스 접근을 RestTemplate으로 변경
  src/main/java/com/gamsung/backend/BackendApplication.java
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/main/java/com/gamsung/backend/global/config/RedisConfig.java
  src/main/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepository.java
  src/main/java/com/gamsung/backend/global/jwt/repository/RedisRepository.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
Labels: Feat, Refactor

#38 JWT Redis Repository 통합테스트 코드 작성
  src/main/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepository.java
  src/test/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepositoryTest.java
Labels: Fix, Test

#43 github actions 스크립트 작성
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  appspec.yml
  build.gradle
Labels: Chore

#44 프론트 개발용 서버 2차 수정
  .env.example
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  appspec.yml
  build.gradle
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: Deploy

#45 Merge pull request #39 from FAST-gamsungcoding/develop
  .github/workflows/CD.yml
Labels: Deploy

#46 Fix: CD.yml 수정
  .github/workflows/CD.yml
Labels: Deploy

#47 Merge pull request #39 from FAST-gamsungcoding/develop
  appspec.yml
  src/main/resources/application-prod.yaml
Labels: Deploy

#48 배포 시 발생했던 오류들 수정
  .github/workflows/CD.yml
  appspec.yml
  scripts/check_server.sh
  scripts/move_server_jar.sh
  scripts/server_start.sh
  scripts/server_stop.sh
  src/main/resources/application-prod.yaml
Labels: Fix

#49 프론트 개발용 서버 3차 배포(배포 스크립트 수정)
  appspec.yml
  scripts/check_server.sh
  scripts/move_server_jar.sh
  scripts/server_start.sh
  scripts/server_stop.sh
Labels: Fix, Deploy

#40 Feat : Global로 쓰이는 클래스들 뼈대 구축
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java
  src/main/java/com/gamsung/backend/global/common/ApiResponse.java
  src/main/java/com/gamsung/backend/global/common/BaseException.java
  src/main/java/com/gamsung/backend/global/common/BaseTime.java
  src/main/java/com/gamsung/backend/global/common/ErrorCode.java
  src/main/java/com/gamsung/backend/global/common/GlobalExceptionHandler.java
Labels: Feat

#55 MemberAuthArgumentResolver 추가
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/global/common/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/config/WebMvcConfig.java
  src/main/java/com/gamsung/backend/global/resolver/AuthContext.java
  src/main/java/com/gamsung/backend/global/resolver/MemberAuth.java
  src/main/java/com/gamsung/backend/global/resolver/MemberAuthArgumentResolver.java
Labels: Feat

#58 BaseTime 수정
  src/main/java/com/gamsung/backend/domain/member/entity/Member.java
  src/main/java/com/gamsung/backend/global/common/BaseTime.java
Labels: Fix

#60 배포 시 ddl-auto 관련 설정 수정
  src/main/resources/application-prod.yaml
Labels: Fix

#64 GlobalException 관련 수정
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/domain/member/exception/MemberAlreadyExistedException.java
  src/main/java/com/gamsung/backend/domain/member/exception/MemberLoginWrongPasswordException.java
  src/main/java/com/gamsung/backend/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/gamsung/backend/global/common/ControllerResponse.java
  src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/exception/UnAuthException.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
Labels: Feat

#66 멤버 관련 API의 통합 테스트 코드 작성
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/test/java/com/gamsung/backend/global/common/BaseIntegrationTest.java
  src/test/java/com/gamsung/backend/global/factory/MemberTestFactory.java
  src/test/java/com/gamsung/backend/integration/MemberIntegrationTest.java
Labels: Test

#73 Fix: cors preflight 관련 설정 추가
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
Labels: Fix

#61 ApiResponse 절충안
  src/main/java/com/gamsung/backend/global/common/ApiResponse.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
Labels: Refactor, Discussion

#65 Open Api 를 활용한 숙박 정보 추가 기능
  .env.example
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/java/com/gamsung/backend/domain/accomodation/entity/Location.java
  src/main/java/com/gamsung/backend/domain/accomodation/repository/AccomodationRepository.java
  src/main/java/com/gamsung/backend/domain/image/entity/Image.java
  src/main/java/com/gamsung/backend/global/openapi/OpenApiService.java
  src/main/java/com/gamsung/backend/global/openapi/UrlConstants.java
  src/main/resources/application.yaml
Labels: Feat

#78 멤버 도메인 부분을 APIResponse 절충안으로 변경
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
Labels: Refactor

#81 JwtPayload에 멤버 ID 추가
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationToken.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/main/java/com/gamsung/backend/global/resolver/AuthContext.java
  src/main/java/com/gamsung/backend/global/resolver/MemberAuthArgumentResolver.java
  src/test/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepositoryTest.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
Labels: Feat

#84 에러 메세지 추가
  src/main/java/com/gamsung/backend/global/exception/ErrorMessage.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
Labels: Feat

#89 SecurityFilterConfig 수정
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
  src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
  src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
Labels: Fix, Feat

#91 import.sql 추가
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/resources/import.sql
Labels: Feat

#92 프론트 개발용 서버 6차 배포 (import.sql 추가)
  .env.example
  .github/workflows/CI.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
  src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/BookDateAvailableResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/OrderAccommodationResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutOrder.java
  src/main/java/com/gamsung/backend/domain/order/entity/Order.java
  src/main/java/com/gamsung/backend/domain/order/exception/BookDateUnavailableException.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderErrorCode.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderExceptionHandler.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderNotFoundException.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderSoldOutException.java
  src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
  src/main/java/com/gamsung/backend/domain/orders/controller/OrdersController.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/main/resources/application-test.yaml
  src/main/resources/import.sql
  src/test/java/com/gamsung/backend/BackendApplicationTests.java
  src/test/java/com/gamsung/backend/global/common/BaseIntegrationTest.java
  src/test/java/com/gamsung/backend/global/common/BaseRedisContainerTest.java
  src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
  src/test/java/com/gamsung/backend/global/jwt/repository/JwtRedisRepositoryTest.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
  src/test/java/com/gamsung/backend/integration/MemberIntegrationTest.java
Labels: Deploy

#96 프론트 개발용 서버 7차 배포 (accommodation 수정)
  src/main/java/com/gamsung/backend/BackendApplication.java
  src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/AccommodationDetailResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/AccommodationSummaryResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/entity/Accommodation.java
  src/main/java/com/gamsung/backend/domain/accommodation/entity/Location.java
  src/main/java/com/gamsung/backend/domain/accommodation/exception/AccommodationNotFoundException.java
  src/main/java/com/gamsung/backend/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/gamsung/backend/domain/accommodation/service/AccommodationService.java
  src/main/java/com/gamsung/backend/domain/accomodation/controller/AccomodationController.java
  src/main/java/com/gamsung/backend/domain/accomodation/dto/response/AccomodationDetailResponse.java
  src/main/java/com/gamsung/backend/domain/accomodation/exception/AccomodationNotFoundException.java
  src/main/java/com/gamsung/backend/domain/accomodation/repository/AccomodationRepository.java
  src/main/java/com/gamsung/backend/domain/accomodation/service/AccomodationService.java
  src/main/java/com/gamsung/backend/domain/image/entity/Image.java
  src/main/java/com/gamsung/backend/domain/image/exception/ImageNotFoundException.java
  src/main/java/com/gamsung/backend/domain/image/repository/ImageRepository.java
  src/main/java/com/gamsung/backend/domain/image/service/ImageService.java
  src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
  src/main/java/com/gamsung/backend/global/openapi/OpenApiService.java
  src/main/java/com/gamsung/backend/global/openapi/UrlConstants.java
  src/main/resources/import.sql
Labels: Deploy

#104 리프레시 토큰 요청 형식 수정
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenControllerRequest.java
  src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenRequest.java
  src/test/http/member/refresh.http
Labels: Fix

#107 develop 브랜치 컨플릭트 수정
  src/main/java/com/gamsung/backend/domain/cart/dto/response/CartFindResponse.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
Labels: Fix

#112 Fix: Order 수정 - transactional readonly 추가
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Labels: Fix

#113 프론트 개발용 서버 9차 배포
  build.gradle
  http/accommodation/find_accommodation.http
  http/member/log_out.http
  http/member/sign_in.http
  http/member/sign_up.http
  http/order/find_order.http
  http/order/order.http
  src/main/java/com/gamsung/backend/domain/accommodation/entity/Accommodation.java
  src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartDeleteRequest.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java
  src/main/java/com/gamsung/backend/domain/cart/dto/response/CartFindResponse.java
  src/main/java/com/gamsung/backend/domain/cart/entity/Cart.java
  src/main/java/com/gamsung/backend/domain/cart/exception/CartException.java
  src/main/java/com/gamsung/backend/domain/cart/repository/CartRepository.java
  src/main/java/com/gamsung/backend/domain/cart/service/CartService.java
  src/main/java/com/gamsung/backend/domain/image/entity/Image.java
  src/main/java/com/gamsung/backend/domain/image/exception/ImageNotFoundException.java
  src/main/java/com/gamsung/backend/domain/member/entity/Member.java
  src/main/java/com/gamsung/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutErrorResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutOrder.java
  src/main/java/com/gamsung/backend/domain/order/entity/Order.java
  src/main/java/com/gamsung/backend/domain/order/exception/BookDateUnavailableException.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderErrorCode.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderExceptionHandler.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderNotFoundException.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderSoldOutException.java
  src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/gamsung/backend/domain/order/repository/OrderRepositorySupport.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
  src/main/java/com/gamsung/backend/global/config/QueryDslConfig.java
  src/main/java/com/gamsung/backend/global/config/UserDetailsConfig.java
  src/main/java/com/gamsung/backend/global/exception/BookDateUnavailableException.java
  src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenControllerRequest.java
  src/main/java/com/gamsung/backend/global/jwt/controller/request/RefreshAccessTokenRequest.java
  src/main/java/com/gamsung/backend/global/openapi/OpenApiService.java
  src/main/java/com/gamsung/backend/global/openapi/UrlConstants.java
  src/main/resources/import.sql
  src/test/http/member/login.http
  src/test/http/member/refresh.http
  src/test/http/member/register.http
Labels: Deploy

#115 멤버 도메인 유닛 테스트 추가
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/gamsung/backend/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/gamsung/backend/domain/member/service/MemberServiceTest.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
  src/test/java/com/gamsung/backend/global/security/WithMockCustomJWTSecurityContextFactory.java
  src/test/java/com/gamsung/backend/global/security/WithMockCustomMember.java
Labels: Test

#118 JwtExceptionFilter 추가
  src/main/java/com/gamsung/backend/global/config/SecurityConfig.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtExceptionFilter.java
Labels: Feat

#117 Refactor : 공통 예외 추가
  src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartDeleteRequest.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java
  src/main/java/com/gamsung/backend/domain/cart/exception/CartException.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java
  src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/exception/ValidationCode.java
Labels: Feat

#119 프론트 개발용 서버 10차 배포 (에러처리 관련 수정)
  .gitignore
  src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartDeleteRequest.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java
  src/main/java/com/gamsung/backend/domain/cart/exception/CartException.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java
  src/main/java/com/gamsung/backend/global/config/SecurityConfig.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/exception/ValidationCode.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtExceptionFilter.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/gamsung/backend/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/gamsung/backend/domain/member/service/MemberServiceTest.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
  src/test/java/com/gamsung/backend/global/security/WithMockCustomJWTSecurityContextFactory.java
  src/test/java/com/gamsung/backend/global/security/WithMockCustomMember.java
Labels: Deploy

#128 Docs/order 수정
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
Labels: Docs

#129 Feat: Order 컨트롤러 수정
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
Labels: Feat

#131 Docs: 멤버 도메인 Swagger 수정
  src/main/java/com/gamsung/backend/domain/member/controller/MemberController.java
  src/main/java/com/gamsung/backend/global/config/SwaggerConfig.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
Labels: Docs

#125 Open API호출 시 cotent-type 지정
  src/main/java/com/gamsung/backend/domain/accommodation/entity/Location.java
  src/main/java/com/gamsung/backend/global/openapi/OpenApiService.java
  src/main/java/com/gamsung/backend/global/openapi/UrlConstants.java
Labels: Feat

#138 Feat: Order 반환값 수정
  src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java
Labels: Feat

#137 로그인 응답 수정
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
Labels: Feat

#139 프론트 개발용 서버 13차 배포 (로그인 응답 수정)
  src/main/java/com/gamsung/backend/domain/accommodation/entity/Location.java
  src/main/java/com/gamsung/backend/domain/cart/service/CartService.java
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/gamsung/backend/domain/member/service/MemberService.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/OrderResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutErrorResponse.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/SoldOutOrder.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
  src/main/java/com/gamsung/backend/global/openapi/OpenApiService.java
  src/main/java/com/gamsung/backend/global/openapi/UrlConstants.java
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
Labels: Feat

#140 Feat/order 조회 total_page 추가
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/FindOrderListResponse.java
  src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Labels: Feat

#141 메인 응답에 totalPage 추가 및 페이지 시작을 1로 수정
  src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/AccommodationSummaryListResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/service/AccommodationService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: Feat

#142 Feat: Order 조회 total_page 추가
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/FindOrderListResponse.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
Labels: Feat

#144 프론트 개발용 서버 14차 배포(page 관련 수정)
  src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/AccommodationSummaryListResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/service/AccommodationService.java
  src/main/java/com/gamsung/backend/domain/order/controller/OrderController.java
  src/main/java/com/gamsung/backend/domain/order/dto/response/FindOrderListResponse.java
  src/main/java/com/gamsung/backend/domain/order/repository/OrderRepository.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: Feat

#147 배포 서버의 설정 수정
  scripts/check_server.sh
  scripts/move_server_jar.sh
  scripts/server_start.sh
  src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java
  src/main/resources/application-prod.yaml
  src/main/resources/logback-spring.xml
Labels: Fix, Refactor

#149 멤버 관련 컨트롤러 유닛 테스트 실패 케이스 추가
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
Labels: Test

#150 프론트 개발용 서버 15차 배포(설정 관련 수정)
  scripts/check_server.sh
  scripts/move_server_jar.sh
  scripts/server_start.sh
  src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/gamsung/backend/global/config/SecurityFilterConfig.java
  src/main/resources/application-prod.yaml
  src/main/resources/logback-spring.xml
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
Labels: Deploy

#151 프론트 개발용 서버 16차 배포(Cors 관련 수정)
  src/main/java/com/gamsung/backend/global/config/CorsConfig.java
Labels: Deploy

#154 JWT 액세스 토큰 리프레시 오류 수정
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/http/member/refresh.http
Labels: Fix

#155 프론트 개발용 서버 17차 배포(액세스 토큰 리프레시 관련 수정)
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/http/member/refresh.http
Labels: Deploy

#157 JWT 서비스 및 프로바이더 수정
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/repository/JwtRefreshTokenRedisRepository.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
  src/test/java/com/gamsung/backend/global/jwt/repository/JwtRefreshTokenRedisRepositoryTest.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
Labels: Refactor

#158 리프레시 이후 기존 액세스 토큰 처리방식 추가
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
Labels: Feat

#160 Test: Order 통합테스트
  src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java
  src/test/java/com/gamsung/backend/domain/order/controller/OrderControllerIntegrationTest.java
Labels: Test

#148 README.md 추가
  .env.example
  README.md
  docs/RUNNING_SCREEN.md
  docs/images/ERD.png
  docs/images/SERVER_STRUCTURE.png
  docs/images/running/멤버_로그아웃_요청.png
  docs/images/running/멤버_로그아웃_응답.png
  docs/images/running/멤버_로그인_요청.png
  docs/images/running/멤버_로그인_응답.png
  docs/images/running/멤버_액세스토큰리프레시_요청.png
  docs/images/running/멤버_액세스토큰리프레시_응답.png
  docs/images/running/멤버_회원가입_요청.png
  docs/images/running/멤버_회원가입_응답.png
  docs/images/running/멤버_회원가입이메일체크_요청.png
  docs/images/running/멤버_회원가입이메일체크_응답.png
  docs/images/running/숙박_개별상품조회_요청.png
  docs/images/running/숙박_개별상품조회_응답.png
  docs/images/running/숙박_메인화면_요청.png
  docs/images/running/숙박_메인화면_응답.png
  docs/images/running/장바구니_등록_요청.png
  docs/images/running/장바구니_등록_응답.png
  docs/images/running/장바구니_삭제_요청.png
  docs/images/running/장바구니_삭제_응답.png
  docs/images/running/장바구니_조회_요청.png
  docs/images/running/장바구니_조회_응답.png
  docs/images/running/주문_결제_요청.png
  docs/images/running/주문_결제_응답.png
  docs/images/running/주문_나의예약내역조회_요청.png
  docs/images/running/주문_나의예약내역조회_응답.png
  docs/images/running/주문_나의예약내역조회_응답2.png
  docs/images/running/주문_나의예약내역조회_응답3.png
  docs/images/running/주문_예약가능여부조회_요청.png
  docs/images/running/주문_예약가능여부조회_응답.png
  http/member/log_out.http
  http/member/login.http
  http/member/logout.http
  http/member/refresh.http
  http/member/register.http
  http/member/registerEmailCheck.http
  http/member/sign_in.http
  http/member/sign_up.http
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
Labels: Docs

#162 TRAVELER API 서버 18차 배포
  .env.example
  README.md
  docs/RUNNING_SCREEN.md
  docs/images/ERD.png
  docs/images/SERVER_STRUCTURE.png
  docs/images/running/멤버_로그아웃_요청.png
  docs/images/running/멤버_로그아웃_응답.png
  docs/images/running/멤버_로그인_요청.png
  docs/images/running/멤버_로그인_응답.png
  docs/images/running/멤버_액세스토큰리프레시_요청.png
  docs/images/running/멤버_액세스토큰리프레시_응답.png
  docs/images/running/멤버_회원가입_요청.png
  docs/images/running/멤버_회원가입_응답.png
  docs/images/running/멤버_회원가입이메일체크_요청.png
  docs/images/running/멤버_회원가입이메일체크_응답.png
  docs/images/running/숙박_개별상품조회_요청.png
  docs/images/running/숙박_개별상품조회_응답.png
  docs/images/running/숙박_메인화면_요청.png
  docs/images/running/숙박_메인화면_응답.png
  docs/images/running/장바구니_등록_요청.png
  docs/images/running/장바구니_등록_응답.png
  docs/images/running/장바구니_삭제_요청.png
  docs/images/running/장바구니_삭제_응답.png
  docs/images/running/장바구니_조회_요청.png
  docs/images/running/장바구니_조회_응답.png
  docs/images/running/주문_결제_요청.png
  docs/images/running/주문_결제_응답.png
  docs/images/running/주문_나의예약내역조회_요청.png
  docs/images/running/주문_나의예약내역조회_응답.png
  docs/images/running/주문_나의예약내역조회_응답2.png
  docs/images/running/주문_나의예약내역조회_응답3.png
  docs/images/running/주문_예약가능여부조회_요청.png
  docs/images/running/주문_예약가능여부조회_응답.png
  http/cart/cart_delete.http
  http/cart/cart_save.http
  http/cart/find_cart.http
  http/member/log_out.http
  http/member/login.http
  http/member/logout.http
  http/member/refresh.http
  http/member/register.http
  http/member/registerEmailCheck.http
  http/member/sign_in.http
  http/member/sign_up.http
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java
  src/main/java/com/gamsung/backend/domain/order/dto/request/OrderAccommodationRequest.java
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/repository/JwtRefreshTokenRedisRepository.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/main/resources/import.sql
  src/test/java/com/gamsung/backend/domain/order/controller/OrderControllerIntegrationTest.java
  src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
  src/test/java/com/gamsung/backend/global/jwt/repository/JwtRefreshTokenRedisRepositoryTest.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
  src/test/java/com/gamsung/backend/integration/CartIntegrationTest.java
Labels: Deploy
