Repository FAST-gamsungcoding/BE_MiniProject, pull requests merged in 2023-12, with the labels that each got.

#171 Feature/accommodations/main
  src/main/java/com/gamsung/backend/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/summary/AccommodationSummaryListResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/summary/AccommodationSummaryResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/gamsung/backend/domain/accommodation/service/AccommodationService.java
  src/main/java/com/gamsung/backend/global/openapi/dto/AccommodationDescriptionDto.java
Labels: Feat, Refactor

#176 global 폴더 리팩토링
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/detail/AccommodationDetailResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/dto/response/summary/AccommodationSummaryListResponse.java
  src/main/java/com/gamsung/backend/domain/accommodation/entity/Accommodation.java
  src/main/java/com/gamsung/backend/domain/accommodation/service/AccommodationService.java
  src/main/java/com/gamsung/backend/domain/cart/controller/CartController.java
  src/main/java/com/gamsung/backend/domain/cart/dto/request/CartEntryRequest.java
  src/main/java/com/gamsung/backend/domain/cart/dto/response/CartFindResponse.java
  src/main/java/com/gamsung/backend/domain/cart/entity/Cart.java
  src/main/java/com/gamsung/backend/domain/cart/exception/CartException.java
  src/main/java/com/gamsung/backend/domain/cart/service/CartService.java
  src/main/java/com/gamsung/backend/domain/image/entity/Image.java
  src/main/java/com/gamsung/backend/domain/image/exception/ImageNotFoundException.java
  src/main/java/com/gamsung/backend/domain/image/repository/ImageRepository.java
  src/main/java/com/gamsung/backend/domain/image/service/ImageService.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/com/gamsung/backend/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/gamsung/backend/domain/member/entity/Member.java
  src/main/java/com/gamsung/backend/domain/order/exception/BookDateUnavailableException.java
  src/main/java/com/gamsung/backend/domain/order/exception/OrderExceptionHandler.java
  src/main/java/com/gamsung/backend/domain/order/service/OrderService.java
  src/main/java/com/gamsung/backend/global/config/SwaggerConfig.java
  src/main/java/com/gamsung/backend/global/config/UserDetailsConfig.java
  src/main/java/com/gamsung/backend/global/exception/BaseException.java
  src/main/java/com/gamsung/backend/global/exception/ErrorCode.java
  src/main/java/com/gamsung/backend/global/exception/ForbiddenException.java
  src/main/java/com/gamsung/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gamsung/backend/global/exception/UnAuthException.java
  src/main/java/com/gamsung/backend/global/exception/ValidationCode.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtExceptionFilter.java
  src/main/java/com/gamsung/backend/global/openapi/dto/AccommodationInfoDto.java
  src/main/java/com/gamsung/backend/global/openapi/dto/RoomInfoDto.java
  src/main/java/com/gamsung/backend/global/openapi/service/OpenApiService.java
  src/test/java/com/gamsung/backend/domain/accomodation/controller/AccommodationControllerTest.java
  src/test/java/com/gamsung/backend/global/factory/AccommodationWithImagesTestFactory.java
  src/test/java/com/gamsung/backend/integration/CartIntegrationTest.java
Labels: Refactor

#179 JWT 관련 리팩토링
  src/main/java/com/gamsung/backend/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/gamsung/backend/global/jwt/JwtPair.java
  src/main/java/com/gamsung/backend/global/jwt/JwtProvider.java
  src/main/java/com/gamsung/backend/global/jwt/controller/JwtController.java
  src/main/java/com/gamsung/backend/global/jwt/dto/JwtPair.java
  src/main/java/com/gamsung/backend/global/jwt/dto/JwtPayload.java
  src/main/java/com/gamsung/backend/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/gamsung/backend/global/jwt/service/JwtService.java
  src/test/java/com/gamsung/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/gamsung/backend/domain/member/service/MemberServiceTest.java
  src/test/java/com/gamsung/backend/domain/order/controller/OrderControllerIntegrationTest.java
  src/test/java/com/gamsung/backend/global/jwt/JwtProviderTest.java
  src/test/java/com/gamsung/backend/global/jwt/controller/JwtControllerTest.java
  src/test/java/com/gamsung/backend/global/jwt/service/JwtServiceTest.java
Labels: Refactor

#181 Refactor : 클래스 명 변경 및 삭제
  src/main/java/com/gamsung/backend/domain/cart/Util/CartConstantNumber.java
  src/main/java/com/gamsung/backend/domain/cart/service/CartService.java
Labels: Deploy

#183 Readme 수정
  README.md
Labels: Docs
